before_install:
  - sudo apt-get update -qq
  - sudo apt-get install debhelper autotools-dev iptables-dev build-essential devscripts dh-autoreconf
script:
  - debuild -i -us -uc -b
  - sudo dpkg -i ../*.deb
